site_name: GearBot
theme:
   name: spacelab
nav:
  - Home: 'index.md'
  - Commands: 'commands.md'
  - Guides:
      - Adding Gearbot: 'Guides/adding_gearbot.md'
      - Configuring the prefix: 'Guides/prefix.md'
      - Introduction to permissions: 'Guides/basic_permissions.md'
      - Setting a language: 'Guides/language.md'
      - Assigning special roles: 'Guides/management_roles.md'
      - Reconfiguring command requirements: 'Guides/overrides.md'
      - Logging: 'Guides/logging.md'
      - Censoring: 'Guides/censoring.md'
      - Self assignable roles: 'Guides/selfroles.md'
      - Custom Commands: 'Guides/custom_commands.md'
      - Misc tweaks: 'Guides/misc.md'
      - Ignoring channels: 'Guides/ignored_channels.md'
      - Archiving: 'Guides/archiving.md'
      - Infractions: 'Guides/infractions.md'
  - Supporting: 'supporting.md'
